# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-23 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=5, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'curriculum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupcode', models.CharField(db_column='groupCode', max_length=10, unique=True)),
            ],
            options={
                'db_table': 'group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Implementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p1', models.IntegerField(blank=True, null=True)),
                ('p2', models.IntegerField(blank=True, null=True)),
                ('p3', models.IntegerField(blank=True, null=True)),
                ('p4', models.IntegerField(blank=True, null=True)),
                ('p5', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'implementation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherid', models.CharField(db_column='teacherID', max_length=10, unique=True)),
                ('firstname', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'teacher',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.CreateModel(
            name='ImplementationGroup',
            fields=[
                ('implementationid', models.ForeignKey(db_column='implementationid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tutorial.Implementation')),
            ],
            options={
                'db_table': 'implementation_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImplementationTeacher',
            fields=[
                ('implementationid', models.ForeignKey(db_column='implementationid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tutorial.Implementation')),
            ],
            options={
                'db_table': 'implementation_teacher',
                'managed': False,
            },
        ),
    ]
